In [1]:
import numpy as np

In [15]:
a = range(10000)
b = np.arange(10000)

In [16]:
%timeit sum(a)

238 µs ± 10.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [17]:
%timeit sum(b)

1.07 ms ± 63.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [18]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
a = np.array([0,1,2,3])
a

In [20]:
type(a)

numpy.ndarray

In [21]:
a.dtype

dtype('int32')

In [22]:
np.array([0,1,2,3], dtype=np.uint8)

array([0, 1, 2, 3], dtype=uint8)

In [34]:
b = np.array([[1,2][3,4]])

TypeError: list indices must be integers or slices, not tuple

In [28]:
b.shape

(10000,)

In [29]:
b.size

10000

In [30]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

In [33]:
a + b

ValueError: operands could not be broadcast together with shapes (4,) (10000,) 

In [36]:
a = np.array([[0,1,2,3],[10,11,12,13]])
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [38]:
a[1,3]

13

In [39]:
a = np.array([10,11,12,13,14])

In [40]:
a

array([10, 11, 12, 13, 14])

In [41]:
a[1:3]


array([11, 12])

In [42]:
a[:3]

array([10, 11, 12])

In [43]:
a[:-2
 ]

array([10, 11, 12])

In [44]:
a[1:-2]

array([11, 12])

In [45]:
a[::2]

array([10, 12, 14])

In [47]:
a = np.arange(5)

In [48]:
a

array([0, 1, 2, 3, 4])

In [50]:
b = a[2:4]
b

array([2, 3])

In [52]:
b[0] = 100
b


array([100,   3])

In [53]:
a

array([  0,   1, 100,   3,   4])

In [54]:
a = np.arange(0,80,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70])

In [55]:
indices = [1,2,-3]

In [56]:
a[indices]

array([10, 20, 50])

In [58]:
mask = np.array([0,1,1,0,0,1,0,0], dtype=np.bool)
mask

array([False,  True,  True, False, False,  True, False, False])

In [59]:
a[mask
 ]

array([10, 20, 50])

In [60]:
mask = a<30
mask

array([ True,  True,  True, False, False, False, False, False])

In [61]:
a[mask]

array([ 0, 10, 20])

In [64]:
a[a==35]

False

In [68]:
np.nonzero([a<30])

TypeError: '<' not supported between instances of 'list' and 'int'

In [67]:
np.nonzero([0,0,1,0])

(array([2], dtype=int64),)

In [69]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [70]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [75]:
a=np.empty(2)
a.fill(0.5)
a

array([0.5, 0.5])

In [73]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [77]:
np.linspace(0,0.9,10)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [92]:
a = np.array([[1,7,3],[8,5,6]])
a

array([[1, 7, 3],
       [8, 5, 6]])

In [81]:
a.sum()

21

In [93]:
a.mean()
a

array([[1, 7, 3],
       [8, 5, 6]])

In [83]:
a.mean()

3.5

In [84]:
a.std()

1.707825127659933

In [85]:
a.min()

1

In [95]:
a.max(axis=0
     )

array([8, 7, 6])

In [96]:
a.argmin()

0

In [98]:
a.argmax()

3

In [99]:
np.all(a>5)

False

In [101]:
a = np.arange(-15,15).reshape(5,6) ** 2
a

array([[225, 196, 169, 144, 121, 100],
       [ 81,  64,  49,  36,  25,  16],
       [  9,   4,   1,   0,   1,   4],
       [  9,  16,  25,  36,  49,  64],
       [ 81, 100, 121, 144, 169, 196]], dtype=int32)

In [102]:
a.max()

225

In [103]:
a.max(axis=0)

array([225, 196, 169, 144, 169, 196], dtype=int32)

In [104]:
a.max(axis=1)

array([225,  81,   9,  64, 196], dtype=int32)

In [105]:
a.mean()

75.16666666666667

In [106]:
a.mean(axis=0)

array([81., 76., 73., 72., 73., 76.])

In [113]:
b = a[:,2]

In [114]:
c = a[:,3]

In [115]:
b + c

array([313,  85,   1,  61, 265], dtype=int32)

In [116]:
a[:,1] + a[:,2] 

array([365, 113,   5,  41, 221], dtype=int32)